# Generated by Django 2.1.7 on 2019-04-03 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ofertas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Atributo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=64)),
            ],
        ),
        migrations.RemoveField(
            model_name='oferta',
            name='id',
        ),
        migrations.RemoveField(
            model_name='requerimiento',
            name='id',
        ),
        migrations.AlterField(
            model_name='oferta',
            name='titulo',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='requerimiento',
            name='requerimiento',
            field=models.TextField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='atributo',
            name='oferta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ofertas.Oferta'),
        ),
        migrations.AlterUniqueTogether(
            name='atributo',
            unique_together={('oferta', 'nombre')},
        ),
    ]
