# Generated by Django 2.2 on 2019-04-02 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('correo', models.CharField(max_length=256, primary_key=True, serialize=False)),
                ('contrasenia', models.CharField(max_length=256)),
            ],
        ),
    ]
