# Generated by Django 2.1.7 on 2019-04-03 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('username', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nombres', models.CharField(default=' ', max_length=30)),
                ('apellidos', models.CharField(default=' ', max_length=30)),
                ('email', models.EmailField(default=' ', max_length=254)),
                ('universidad', models.CharField(default=' ', max_length=40)),
                ('fechaNacimiento', models.DateField(null=True)),
                ('contrasenia', models.CharField(default=' ', max_length=250)),
            ],
        ),
    ]
